#write a program to print sum of two numbers
#a=int(input("enter first number:"))
#b=int(input("enter second number:"))
#print(a+b)
#write a program to print area and perimeter of square rectangle and circle
#a = int(input("Enter first number: "))
#b = int(input("Enter second number: "))
#print("area of square:", a * a)
#a = int(input("Enter length of rectangle: "))
#b = int(input("Enter breadth of rectangle: "))
#print("Area of rectangle:", a * b)
#a=int(input("Enter radius of circle: "))
#print("Area of circle:", 3.14 * a * a)
#a = int(input("Enter side of square: "))
#print("perimeter of square:", 4 * a)
#a = int(input("Enter length of rectangle: "))
#b = int(input("Enter breadth of rectangle: "))
#print("Perimeter of rectangle:", 2 * (a + b))
#a=int(input("Enter radius of circle: "))
#print("Perimeter of circle:", 2 * 3.14 * a)
